# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     Layout/EndAlignment:
#       Enabled: true
#

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
# @NOTE: changed EnforcedStyleAlignWith from "keyword" to "variable"
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

# @NOTE: changed EnforcedStyle from "with_first_parameter" to "with_fixed_indentation"
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Layout/LineLength:
  Max: 120
  AllowCopDirectives: true
  AllowedPatterns: ['\s#\s|^#\s'] # allows comments to overflow the line length. E.g. for URLs
  Exclude:
    - 'spec/**/*'
